package ch.and.pokemonpastropgo.db

import android.content.Context
import android.util.Log
import androidx.room.Database
import androidx.room.Room
import androidx.room.RoomDatabase
import androidx.sqlite.db.SupportSQLiteDatabase
import ch.and.pokemonpastropgo.db.dao.HuntZoneDAO
import ch.and.pokemonpastropgo.db.dao.NotAPokemonDAO
import ch.and.pokemonpastropgo.db.dao.PokemonToHuntDAO
import ch.and.pokemonpastropgo.db.models.HuntZone
import ch.and.pokemonpastropgo.db.models.NotAPokemon
import ch.and.pokemonpastropgo.db.models.PokemonToHunt
import kotlin.concurrent.thread

@Database(
    entities =[HuntZone::class,NotAPokemon::class,PokemonToHunt::class],
    version = 1,
    exportSchema = true
)
abstract  class PPTGDatabase:  RoomDatabase() {
    abstract fun huntZoneDAO(): HuntZoneDAO
    abstract fun pokemonToHuntDAO(): PokemonToHuntDAO
    abstract fun notAPokemonDAO(): NotAPokemonDAO

    companion object{
        private var INSTANCE: PPTGDatabase? = null

        fun getDB(context: Context): PPTGDatabase{
            return INSTANCE?: synchronized(this){
                INSTANCE = Room.databaseBuilder(context.applicationContext,
                PPTGDatabase::class.java,"pptg_db.db")
                    .fallbackToDestructiveMigration()
                    .addCallback(PPTGDatabaseCallBack())
                    .build()

                INSTANCE!!.query("select 1",null)
                INSTANCE!!
            }
        }
    }

    private class PPTGDatabaseCallBack : RoomDatabase.Callback() {
        override fun onCreate(db: SupportSQLiteDatabase) {
            super.onCreate(db)
            INSTANCE?.let{ database ->
                val isEmpty = database.huntZoneDAO().getAllZonesCount().value == null &&  database.huntZoneDAO().getAllZonesCount().value == null
                Log.d("",isEmpty.toString())
                if(isEmpty){
                    thread {
                        //TODO populate database
                        database.huntZoneDAO().insertAll(
                            HuntZone(
                                null,
                                "HEIG - Cheseaux",
                                "Une zone bondée de pokémouille dans chaque recoins du bâtiment",
                                46.779380,
                                6.659500,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Y-Plage",
                                "vous voulez des pokémouilles aquatique, ici c'est l'endroit idéal pour en trouver",
                                46.785060,
                                6.651450,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "HEIG - St-Roch",
                                "Deuxième domaine le plus populaire pour trouver des pokémouilles unique",
                                46.781230,
                                6.647310,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Chez manu",
                                "Un pokémouille spécial rôde dans les parages, faites attention trouvez le avant qu'il vous trouves",
                                46.540680,
                                6.581140,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "A VV",
                                "Un pokémouille spécial rôde dans les parages, faites attention trouvez le avant qu'il vous trouves",
                                46.46857467860025,
                                6.841636429790459,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Freddy",
                                "Il a une  très grande collection de pokemouilles qu'il à abandonné dans la région",
                                46.4322894285225,
                                6.90917936499722,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Au suchet",
                                "L'aventurier De Marta c'est perdu dans les montagnes, pour laisser une trace de lui il à laissé un trail de pokemouille, vous arriverez peut être à aider ce grand homme en trouvant tout ses pokémouilles",
                                46.774741742693706,
                                6.466013374905819,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Au chasseron",
                                "Le malheureux manu à eu l'idée de faire du vélo avec sa poche ouverte, il a perdu tout ses pokémouilles...",
                                46.85450565982799,
                                6.538690668189977,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "karting",
                                "Le pilote ZonBON à éparpiller toute sa collection de pokémouille sur le circuit ",
                                46.808732749777725,
                                6.561335780253818,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Chez Fabio",
                                "Fabieau est en train de speedrun un nouveau RPG sa soeur à volé tout ses pokémouilles et les a éparpillé dans la zone ",
                                46.7843988104458,
                                6.6311103022575475,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Chez les bobos",
                                "Chaque fois que roro est aller boboisé ici, elle à laissé sa marque",
                                46.521650854065854,
                                6.629604810666031,
                                500.0
                            ),
                            HuntZone(
                                null,
                                "Chez yannick",
                                "Les pokemouilles qu'il à laissé n'apparaissent que à partir de 21h",
                                46.527919698494436,
                                6.649154865163653,
                                500.0
                            ),


                            )
                        database.notAPokemonDAO().insertAll(
                            NotAPokemon("pukachi",""),
                            NotAPokemon("ratatouille",""),
                            NotAPokemon("dreakeau",""),
                            NotAPokemon("boulenormal",""),
                            NotAPokemon("carapace",""),
                            NotAPokemon("nidoroi",""),
                            NotAPokemon("herbivore",""),
                            NotAPokemon("salam",""),
                            NotAPokemon("roukoul",""),
                            NotAPokemon("macho",""),
                        )
                        database.pokemonToHuntDAO().insertAll(
                            PokemonToHunt("pukachi_1","pukachi",1,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("ratatouille_1","ratatouille",1,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("dreakeau_1","dreakeau",1,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("boulenormal_1","boulenormal",1,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("nidoroi_1","nidoroi",1,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("herbivore_1","herbivore",1,"somewhere",false,false,0.0,0.0),

                            PokemonToHunt("salam_2","salam",2,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("ratatouille_2","ratatouille",2,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("boulenormal_2","boulenormal",2,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("herbivore_2","herbivore",2,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("Macho_2","macho",2,"somewhere",false,false,0.0,0.0),

                            PokemonToHunt("nidoroi_3","nidoroi",3,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("Macho_3","macho",3,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("salam_3","salam",3,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("dreakeau_3","dreakeau",3,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt("herbivore_3","herbivore",3,"somewhere",false,false,0.0,0.0),
                            PokemonToHunt(
                                "pukachi_3",
                                "pukachi",
                                3,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_3",
                                "boulenormal",
                                3,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "boulenormal_4",
                                "boulenormal",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_4",
                                "macho",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_4",
                                "dreakeau",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_4",
                                "salam",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "nidoroi_4",
                                "nidoroi",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "ratatouille_4",
                                "ratatouille",
                                4,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_5",
                                "nidoroi",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_5",
                                "macho",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_5",
                                "salam",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_5",
                                "dreakeau",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_5",
                                "herbivore",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_5",
                                "pukachi",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_5",
                                "boulenormal",
                                5,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_6",
                                "nidoroi",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_6",
                                "macho",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_6",
                                "salam",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_6",
                                "dreakeau",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_6",
                                "herbivore",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_6",
                                "pukachi",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_6",
                                "boulenormal",
                                6,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_7",
                                "nidoroi",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_7",
                                "macho",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_7",
                                "salam",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_7",
                                "dreakeau",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_7",
                                "herbivore",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_7",
                                "pukachi",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_7",
                                "boulenormal",
                                7,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_8",
                                "nidoroi",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_8",
                                "macho",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_8",
                                "salam",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_8",
                                "dreakeau",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_8",
                                "herbivore",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_8",
                                "pukachi",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_8",
                                "boulenormal",
                                8,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_9",
                                "nidoroi",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_9",
                                "macho",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_9",
                                "salam",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_9",
                                "dreakeau",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_9",
                                "herbivore",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_9",
                                "pukachi",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_9",
                                "boulenormal",
                                9,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_10",
                                "nidoroi",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_10",
                                "macho",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_10",
                                "salam",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_10",
                                "dreakeau",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_10",
                                "herbivore",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_10",
                                "pukachi",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_10",
                                "boulenormal",
                                10,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_11",
                                "nidoroi",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_11",
                                "macho",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_11",
                                "salam",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_11",
                                "dreakeau",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_11",
                                "herbivore",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_11",
                                "pukachi",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_11",
                                "boulenormal",
                                11,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            PokemonToHunt(
                                "nidoroi_12",
                                "nidoroi",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "Macho_12",
                                "macho",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "salam_12",
                                "salam",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "dreakeau_12",
                                "dreakeau",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "herbivore_12",
                                "herbivore",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "pukachi_12",
                                "pukachi",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),
                            PokemonToHunt(
                                "boulenormal_12",
                                "boulenormal",
                                12,
                                "somewhere",
                                false,
                                false,
                                0.0,
                                0.0
                            ),

                            )
                    }
                }
            }
        }

    }
}